name: deploy
env:
  DOTNET_NOLOGO: true

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 🤘 checkout
        uses: actions/checkout@v2

      - name: ⚙ dotnet 5.0.x
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x

      - name: 📦 publish
        run: dotnet publish -c Release -o publish

      - name: 🖉 base href
        uses: SteveSandersonMS/ghaction-rewrite-base-href@v1
        with:
          html_path: publish/wwwroot/index.html
          base_href: /bold/

      - name: 🚀 deploy
        if: success()
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: publish/wwwroot
          CLEAN: true